language: node_js
node_js:
- lts/*
script:
- npm run lint
- npm run build
- npm run pack
cache: npm
deploy:
  provider: releases
  api_key:
    secure: v0jMoZ37G4eSSWEzo8qoyFzxPMlKqEyKkln3Fig7NdoDRQiU587I5mpr2V53XKANBJq9512DtkhoHld1RAoy3rfzbbw3awIK7Il7ZmpLrEx+yQ95aPiRE3Tp5/MarqtJ7IfOp6pp3uuaGj0lhaLWIb9tXyvFlWhuEnya0scRnMS/EyhHIRsRR2ucxwDXPkUK6xbTcuyAsIEGVCFXecOH0yp5259i8WD3deKApldt3EmqoG2+cMequnfUVUm//QThKxswlv27lyqQ9GuOnSy5iGpQPGLtphh6/vFKXeHnchbdssU5fGWMtighnUSKi6sGr6JUcQpl5ZPUJzXj2PA+rqAjho97GJBV+iqnkmRI7pilBMI8JKbCTI/n/r0bx3B8AXxY7B875vyYpcD0iG/vCCQRtKbIfLIawPBBgFkjGECAPtdqq0NLdrj5mxGLtP+I9vS7i6mhBh2/dxn5PC/4to17L9yfLg68cjMLUSn2NoX3d5SJr0B+mitAa9iWrgvFOPbf/crPqXLTKVgfNgae1DvT0pNg2NyolWp/ICf09waTIrBifLynKaowq9QFOnewRiROIx4RF2rONRFEvVJAk5Js1IvH6dTlDBE6D9VRg93qPAohvqYXO4VmfHWVxu21IkZ1DgSBvT1DH8TR3S4Cry9IkK5phmZyXN2a/1uPlc8=
  skip_cleanup: true
  file:
  - resizeit2.zip
  on:
    repo: fuzzykiller/resizeit2
    tags: true
